edu/urls.py
from django.urls import path
from  .views import *
from  .lesson import *
from django.contrib.auth.views import PasswordChangeView
app_name = 'edu'

urlpatterns = [
  
    path('', index, name='index'),
    path('page/<str:page_name>', page_views, name='page_views'),
    path('course/<str:course_name>/', course_view, name='course_view'),
    path('frontend/', frontend, name='frontend'),
    path('student/<int:user_id>', ProfilView.as_view(), name='student_account'),
    path('teacher/', teacher_account, name='teacher_account'),
    path('tasks/', tasks, name='tasks'),
    path('python/', python, name='python'),
    path('query/result/', query_result, name='query_result'),
    path('<str:katalog_name>/tutorial/<int:number>/<str:slug>/', TaskView.as_view(), name='django'),
    path('recovery/', PasswordChangeView.as_view(template_name='pages/send_password.html'), name='send_password'),
    path('send_message/', accpet_message, name='send_message'),
    path('user/<int:user_id>/<str:course_name>/lessons/list/', lessons, name='lessons'),
    path('insert_course/<int:user_id>/<int:course_id>', insert_course, name='insert_course'),
       
]

templates/student/lessons.html
{% extends 'wrappers/base-wrap.html' %}
{% load static %}
   {% block meta %}
    <meta name="description" content="Django xaqida">
    {% endblock %}
    {% block title %}
    <title>eduPy |Nima uchun Djangoni  o'rganishim kerak</title>
    {% endblock %}
{% block content %}
<section id="lesson">
<div class="container">
	<div class="row">
		<div class="col-md-9">
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">

		<img src="{{ course.image.url }}" width="50%" height="35%" class="img-fluid" alt="Responsive image">
    
	</div>
	<div class="col-md-2"></div>

</div>
  <section class="padding-50-0">
  <div class="container">
  
    <div class="time-line-status">
    <div class="tt-time-status">
        <div class="row justify-content-center">
            <div class="col-md-2">
                <span class="title-status">Identified</span>
            </div>
            <div class="col-md-10">
                <h5 class="title-status-h5">Hong Kong Cloud Server Delays <span>2018-01-08 02:44:11 UTC</span></h5>
                <p class="title-status-p">Orders in Hong Kong are severely delayed due to the extreme demand for our new location. We are expecting the issue to be resolved with all orders delivered within 72 hours. Thank you for your patience.</p>
            </div>
            {% for l in lessons %}

            <div class="status-div-optionel chck">
              {% if forloop.first %}
            
            <p><b><a href="{% url 'edu:django' l.lesson.url l.lesson.number l.lesson.slug  %}" >{{ l.course.title }} {{ forloop.counter }}-dars</b> {{ l.lesson.title }} </a><span>Topshirilmadi <i class="fa fa-circle-o-notch" aria-hidden="true"></i></span></p>
              
              {% else %}
             
              {% if l.avilable %}
                
                <p><b><a href="#">{{ l.course.title }} {{ forloop.counter }}-dars</b> {{ l.lesson.title }} </a><span>Topshirilmadi <i class="fa fa-circle-o-notch" aria-hidden="true"></i></span></p>
             
              {% else %}
              
                <p><b><a href="#">{{ l.course.title }} {{ forloop.counter }}-dars</b> {{ l.lesson.title }}da <i class="fa fa-lock" style="color:white;"></i></a><span>Topshirildi <i class="fa fa-circle-o-notch" aria-hidden="true"></i></span></p>
               
                {% endif %}
                
                {% endif %}
            </div>
            {% endfor %}
      
        </div>
    </div>
    </div>



  </div>
  </section>
		</div>
	<div class="col-md-3">
		<div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <strong class="mr-auto">Bootstrap</strong>
    <small>11 mins ago</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="toast-body">
    Hello, world! This is a toast message.
  </div>
</div>
	          <ul class="list-group mt-5">
          {% for l in lessons %}
          {% if l.lock %}
  <li class="list-group-item" style=";"><i class="fa fa-lock"></i> <a href="#">{{ l.title }}</a></li>
  <!-- Note a custom script is used to activate toasts:
$('.toast').toast();
-->



  {% else %}
    <li class="list-group-item" style=";"><a href="#">{{ l.title }}</a></li>
    {% endif %}
 {% endfor %}
</ul>
	</div>		
	</div>	
</div>
</section>




{% endblock %}	