edu/urls.py
from django.urls import path
from  .views import *
from  .lesson import *
from django.contrib.auth.views import PasswordChangeView
app_name = 'edu'

urlpatterns = [
  
    path('', index, name='index'),
    path('page/<str:page_name>', page_views, name='page_views'),
    path('course/<str:course_name>/', course_view, name='course_view'),
    path('frontend/', frontend, name='frontend'),
    path('student/<int:user_id>', ProfilView.as_view(), name='student_account'),
    path('teacher/', teacher_account, name='teacher_account'),
    path('tasks/', tasks, name='tasks'),
    path('python/', python, name='python'),
    path('query/result/', query_result, name='query_result'),
    path('<str:katalog_name>/tutorial/<int:number>/<str:slug>/', TaskView.as_view(), name='django'),
    path('recovery/', PasswordChangeView.as_view(template_name='pages/send_password.html'), name='send_password'),
    path('send_message/', accpet_message, name='send_message'),
    path('user/<int:user_id>/<str:course_name>/lessons/list/', lessons, name='lessons'),
    path('insert_course/<int:user_id>/<int:course_id>', insert_course, name='insert_course'),
       
]

templates/pages/about.html
{% extends 'wrappers/base.html' %}
{% load static %}
{% block content %}
        <div class="mt-auto header-top-height"></div>
        <main class="container mb-auto">
            <h3 class="mt-3 main-header-text-title"><span>Python va boshqa dasturlash tillarini online o'rgatuvchi tizim</span>&lt;edupy/&gt;
	  <span class="sub-page-breadcrumb"><a href="#">Bosh sahifa</a> - Biz haqimizda</span>
	  </h3>

        </main>
        <div class="mt-auto"></div>
    </div>

<!--     <section class="our-pertners padding-20-0 mr-tp-0">
        <div class="container">
            <h2 class="d-none">our pertners</h2>
            <div class="owl-carousel pertners-carousel owl-theme">
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo1.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo2.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo3.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo4.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo5.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo1.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo2.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo3.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo4.png" alt="" /> </a>
                </div>
                <div class="item">
                    <a href="#"> <img src="img/pertners/logo5.png" alt="" /> </a>
                </div>
            </div>
        </div>
    </section> -->

    <section class="padding-40-0-100 position-relative">
        <div class="container">
            <div class="row justify-content-between">

                <div class="col-md-4 side-text-right-container">
                    <h2 class="side-text-right-title f-size25">Bizning maqsad va vazifalarimiz,<br>Online ta'lim,foydali,qiziqarli</h2>
                    <p class="side-text-right-text f-size16">
                        Maqsadimiz yurtimizning barcha dasturlash va til o'rganishga qiziqishi bor yoshlariga eng sifatli,qiziqarli va yuqori darajadagi online darslarni taqdim etish. Asosiy e'tibor <b>Python</b> dasturlash tiliga qaratilgan.Biroq biz bu bilan chegaralanib qolmay  PHP, Javascript, Java kabi  dasturlash tillari uchun xam sof o'zbek tilida yuqori sifatli darsliklar qo'shib boramiz.Bundan tashqari kurslarimiz sonini ingliz, koreys tillari bilan xam kengaytirish maqsadidamiz 
                        <br>
                    </p>
                    <p>
                        <a class="side-text-right-button" href="{% url 'edu:courses' %}">Biz bilan o'rganing</a>
                    </p>
                </div>

                <div class="col-md-7 our-services-carousel-container">
                    <div class="our-services-carousel">
                          <div class="carousel-cell">
                            <div class="our-services-coresol-box">
                                <i class="fa fa-file-powerpoint mb-3"></i>
                                <h5>Python</h5>
                                <p>Yaqin yillarda ichida reytingning eng yuqori pog'onasida<br>Eng talab ko'payatgan til</p>
                                <a href="{% url 'edu:course_view' 'python' %}"></a>
                            </div>
                        </div>
                        <div class="carousel-cell">
                            <div class="our-services-coresol-box">
                                <i class="fa fa-code mb-3"></i>
                                <h5>Python_Django</h5>
                                <p>Instagram va You-Tube ni '" Ko'tarib"' turgan web frameworkni o'rganing</p>
                                <a href="{% url 'edu:course_view' 'python' %}"></a>
                            </div>
                        </div>
                        <div class="carousel-cell">
                            <div class="our-services-coresol-box">
                                <i class="fab fa-html5 mb-3"></i>
                                <h5>HTML</h5>
                                <p>WEB dasturlashga qiziqadiganlar uchun ilk qadamlar va brauzer tilini o'rganing. </p>
                                <a href="{% url 'edu:course_view' 'html' %}"></a>
                            </div>
                        </div>

                        <div class="carousel-cell">
                            <div class="our-services-coresol-box">
                                <i class="fab fa-css3 mb-3"></i>
                                <h5>CSS</h5>
                                <p>WEB sahifalaringizga "jon" bering , kaskad stillar jadvalini o'rganing! </p>
                                <a href="{% url 'edu:course_view' 'css' %}"></a>
                            </div>
                        </div>

                    </div>

                </div>

            </div>
        </div>
    </section>

    <section class="padding-0-100 position-relative">
        <div class="container">

            <div class="row justify-content-between">

                <div class="col-md-7 about-us-img-section">
                    <img src="/static/svg/video-learningboys.svg" alt="" />
                </div>

                <div class="col-md-4 side-text-right-container d-flex mx-auto flex-column">
                    <div class="mb-auto"></div>
                    <h2 class="side-text-right-title f-size25">Jamoamizda tajribali Python va web full-stack dasturchilar bor<br> </h2>
                    <p class="side-text-right-text f-size16">
              <b>Python</b>
                       va <b>Django</b>da ishlaydigan tajribali dasturchi ustozlarimizdan tashqari yana  jamoamiz a'olari <b>HTML</b> ,<b>CSS</b>, <b>Bootstrap</b>, <b>Javascript</b>,<b>Jquery</b>,<b>Ajax</b>,<b>Java</b>, <b>PHP</b>,<b>C++</b> kabi dasturlash tillari ustalari bor<br> 
                    </p>
                    <p>
                        <a class="side-text-right-button" href="{% url 'edu:page_views' 'courses' %}">Biz bilan o'rganing</a>
                    </p>
                    <div class="mt-auto"></div>
                </div>

            </div>
        </div>
    </section>

 <section class="padding-100-0-0 with-top-border">
        <div class="container">
            <h5 class="title-default-coodiv-two">Nimadan boshlash kerak ?</h5>

            <div class="row justify-content-center mr-tp-40">
                <div class="col-md-9">

                    <div class="accordion" id="frequently-questions">

                        <div class="questions-box">
                            <div id="headingOne">
                                <button class="btn questions-title" type="button" data-toggle="collapse" data-target="#questionone" aria-expanded="true" aria-controls="questionone">
                                   Ro'yhatdan o'tish va darslar
                                </button>
                            </div>

                            <div id="questionone" class="collapse show questions-reponse" aria-labelledby="headingOne" data-parent="#frequently-questions">
                                A'zo bo'ling yoki oldindan ochgan profilingizga kiring. Profilingiz orqali yoki KURSLAR bo'limi orqali kerakli kursni tanlang. <br>Kursga yoziling va intensiv tarzda darslarni olib boring. Darslar vaqtlari kurslarga qarab farq qilishi mumkin. Muhimi o'z yo'nalishingizni <b>BEPUL</b> o'rganing.
                             </div>
                        </div>

                        <div class="questions-box">
                            <div id="headingtwo">
                                <button class="btn questions-title collapsed" type="button" data-toggle="collapse" data-target="#questiontwo" aria-expanded="true" aria-controls="questiontwo">
                                    Umumiy savollar.
                                </button>
                            </div>

                            <div id="questiontwo" class="collapse questions-reponse" aria-labelledby="headingtwo" data-parent="#frequently-questions">
                                <ul class="list-unstyled mt-5 mb-5">
                                    <li class="quest text-primary ">Dars vaqtlari , davomiyligi  qanaqa?</li>
                                    <li class="ans pl-5">Kurs turiga qarab farq qiladi, video davomiyligi max 20-30 minut, matn va rasmli kontentlardan istalgancha foydalanish mumkin.</li>
                                    <li class="quest text-primary"> Topshiriqlar va oraliq nazorat ishlari qanday usulda yuritiladi?</li>
                                    <li class="ans pl-5">Uyga vazifani navbatdagi dars boshlanishiga 4 soat qolguncha topshirish kerak. Oraliq nazorat imtihonlaridan o'ta olmaganlar uchun kelasi imtihon 3 kun ichida </li>
                                    <li class="quest text-primary">Nega aynan shunday qilingan?</li>
                                    <li class="ans pl-5">Bu yosh dasturchilarda Dedlayn muhimi ekanini va loyihani o'z vaqtida topshirish kerakligini singdirish uchun qilingan.</li>
                                    <li class="quest text-primary">Ballar nima uchun kerak?</li>
                                    <li class="ans pl-5"> Ballar yig'ish orqali avvalo kursni yaxshi o'zlashtirasiz va bu orqali chegirmalarga ega bo'lasiz. </li>
                                    <li class="quest text-primary">Qachon ball beriladi ?</li>
                                    <li class="ans pl-5">Kurs ichidagi testlarni yechish orqali (10-15 ball) <br>Online tarzda darslarni kuzatish orqali (2 ball har bir dars uchun) <br>Amaliy mashg'ulotni bajarish orqali (10 ball har bir topshiriqga) </li>
                                    <li class="quest text-primary">Vazifani qilmasa bo'ladimi ?</li>
                                    <li class="ans pl-5"> Avvalo o'ziga havola , lekin kurs rahbari sizni topshiriqlaringizni tekshirib kerakli ballarni qo'yishi uchun vazifani topshirish shart! Navbatdagi darsdan kamida 4 soat  oldin.</li>
                                    <li class="quest text-primary">Talabalar chati (Telegram)</li>
                                    <li class="ans pl-5">Kursdoshlaringiz bilan doimiy aloqada bo'ling ,tajriba almashing. Telegram orqali kurs uchun ochilgan chatlarga a'zo bo'ling.</li>
                                    <li class="quest ">Boshqa savol bor...</li>
                                    <li class="ans pl-5">Barcha savollar bilan istalgan aloqa usullaridan foydalansangiz bo'ladi, telefon, email, sayt orqali xabar qoldirish. </li>

                                </ul>
                            </div>
                        </div>

                        <div class="questions-box">
                            <div id="headingtree">
                                <button class="btn questions-title collapsed" type="button" data-toggle="collapse" data-target="#questiontree" aria-expanded="true" aria-controls="questiontree">
                                    Forum va Chat qoidalari
                                </button>
                            </div>

                            <div id="questiontree" class="collapse questions-reponse" aria-labelledby="headingtree" data-parent="#frequently-questions">
                                Forum va Chatlarda faqat darsga oid savollar, muloqot mavzusi qatiiyan texnik bo'lishi shart! <br>Haqoratlar , mavzudan tashqari gaplar cheklanadi. Portal qoidalariga amal qilamagan talabalarni Administartorlar chetlatish huquqiga ega , jumladan Forum va Chatlarda ham.<br> Portal ma'lumotlari uning yuklovchilarining mulki hiosblanadi ularni o'g'irlash va noodatiy foydalanish qonun bilan taqib qilinadi! Qoidalar bilan Qoidalar bo'limida batafsil tanishing.
                            </div>
                        </div>

                    </div>

                </div>
            </div>

        </div>
    </section>
    <div class="mb-5"></div>
   <section class="footer-section-banner">
        <div class="container">
            <div class="row free-trial-footer-banner">
                <div class="col-md-8">
                    <h5 class="free-trial-footer-banner-title">Bepul sinov kurslarini boshlash uchun hoziroq ro'yhatdan o'ting</h5>
                    <p class="free-trial-footer-banner-text">Chegirmalar vaqti chegaralangan. Dasturlashni o'rganmoqchimisiz? Unda hoziroq ro'yhatdan o'ting. </p>
                </div>

                <div class="col-md-4 free-trial-footer-links d-flex mx-auto flex-column">
                    <div class="mb-auto"></div>
                    <div class="mb-auto">
                        <a class="sign-btn" href="{% url 'edu:page_views' 'signup' %}">Ro'yhatdan o'tish</a>
                        <a class="log-btn" href="{% url 'edu:page_views' 'signin' %}">Kirish</a>
                    </div>
                    <div class="mt-auto"></div>
                </div>
            </div>
        </div>
    </section>
  {% endblock %}

templates/pages/ajax.html
<p></p>
<script>
    /* Article FructCode.com */
$( document ).ready(function() {
    $("#btn").click(
        function(){
            sendAjaxForm('form_messages', 'ajax_contact', '{% url "edu:query_result"%}');
            return false; 
        }
    );
});
 
function sendAjaxForm(form_messages, ajax_contact, url) {
    $.ajax({
        url:     url, //url страницы (action_ajax_form.php)
        type:     "POST", //метод отправки
        dataType: "html", //формат данных
        data: $("#"+ajax_contact).serialize(),  // Сеарилизуем объект
        success: function(response) { //Данные отправлены успешно
            result = $.parseJSON(response);
            console.log(result.status)
            if(result.status == 'ok'){
              // document.getElementById('ul_testing').style='display:none'
              $('#ul_testing').css({'display':'none','transition':'2s'});
              $('#next_lesson').css({'display':'block'});
              $('#my_btn').click();
            }
            // $('#name').val('');
            // $('#email').val('');
            // $('#message').val('');
            $('#form_messages').html('<h5 class="text-success">Qabul qilindi</h5>');
        },
        error: function(response) { // Данные не отправлены
            $('#form_messages').html('<h5 class="text-warning">Xatolik ! <br>Boshqatdan urinib ko`ring</h5>');
        }
    });
}
</script>

templates/pages/beginners.html
{% extends 'wrappers/base.html' %}
{% load static %}
{% block content %}
 <div class="mt-auto header-top-height"></div>
        <main class="container mb-auto">
            <h3 class="mt-3 main-header-text-title"><span> <b>eduPy</b> Dasturlash bo'yicha onlayn o'quv markaz</span>&lt;boshlovchilar/&gt;
              <p class="sub-page-breadcrumb"><a href="#">Bosh sahifa</a> - Boshlash</p>
            </h3>

        </main>
        <div class="mt-auto"></div>
<section class="padding-50-0-10 position-relative pt-5" style="margin-top: 100px;">

        <div class="container pt-5">
            <div class="row justify-content-left box-features-tree-container">
                <div class="col-md-4 box-features-tree">
                    <i class="fas fa-chess-bishop"></i>
                    <h5>Kuchli dasturchi bo'lishni istaysizmi?</h5>
                    <p>Python ni o'rganing. U hozir dunyoda eng mashxur va o'rganish uchun oson tilga aylanib ulgurdi.</p>
                </div>

                <div class="col-md-4 box-features-tree">
                    <i class="far fa-smile-wink"></i>
                    <h5>Yordam berishga tayyormiz</h5>
                    <p>O'qitish usulimiz, dars vaqtida va undan tashqarida talabalarga bo'lgan e'tiborimiz siznni befarq qoldirmaydi.</p>
                </div>

                <div class="col-md-4 box-features-tree">
                    <i class="fas fa-sync-alt"></i>
                    <h5>Takrorlash bu o'sish</h5>
                    <p>Barcha siz o'tgan darslaringizni istalgan vaqtda kirib ko'rishingiz va takrorlashingiz, yuklab olishingiz mumkin.</p>
                </div>
            </div>

        </div>
    </section>
   
 
    <section class="padding-100-0-0 with-top-border">
        <div class="container">
            <h5 class="title-default-coodiv-two">Nimadan boshlash kerak ?</h5>

            <div class="row justify-content-center mr-tp-40">
                <div class="col-md-9">

                    <div class="accordion" id="frequently-questions">

                        <div class="questions-box">
                            <div id="headingOne">
                                <button class="btn questions-title" type="button" data-toggle="collapse" data-target="#questionone" aria-expanded="true" aria-controls="questionone">
                                   Ro'yhatdan o'tish va darslar
                                </button>
                            </div>

                            <div id="questionone" class="collapse show questions-reponse" aria-labelledby="headingOne" data-parent="#frequently-questions">
                                A'zo bo'ling yoki oldindan ochgan profilingizga kiring. Profilingiz orqali yoki KURSLAR bo'limi orqali kerakli kursni tanlang. <br>Kursga yoziling va intensiv tarzda darslarni olib boring. Darslar vaqtlari kurslarga qarab farq qilishi mumkin. Muhimi o'z yo'nalishingizni <b>BEPUL</b> o'rganing.
                             </div>
                        </div>

                        <div class="questions-box">
                            <div id="headingtwo">
                                <button class="btn questions-title collapsed" type="button" data-toggle="collapse" data-target="#questiontwo" aria-expanded="true" aria-controls="questiontwo">
                                    Umumiy savollar.
                                </button>
                            </div>

                            <div id="questiontwo" class="collapse questions-reponse" aria-labelledby="headingtwo" data-parent="#frequently-questions">
                                <ul class="list-unstyled mt-5 mb-5">
                                    <li class="quest text-primary ">Dars vaqtlari , davomiyligi  qanaqa?</li>
                                    <li class="ans pl-5">Kurs turiga qarab farq qiladi, video davomiyligi max 20-30 minut, matn va rasmli kontentlardan istalgancha foydalanish mumkin.</li>
                                    <li class="quest text-primary"> Topshiriqlar va oraliq nazorat ishlari qanday usulda yuritiladi?</li>
                                    <li class="ans pl-5">Uyga vazifani navbatdagi dars boshlanishiga 4 soat qolguncha topshirish kerak. Oraliq nazorat imtihonlaridan o'ta olmaganlar uchun kelasi imtihon 3 kun ichida </li>
                                    <li class="quest text-primary">Nega aynan shunday qilingan?</li>
                                    <li class="ans pl-5">Bu yosh dasturchilarda Dedlayn muhimi ekanini va loyihani o'z vaqtida topshirish kerakligini singdirish uchun qilingan.</li>
                                    <li class="quest text-primary">Ballar nima uchun kerak?</li>
                                    <li class="ans pl-5"> Ballar yig'ish orqali avvalo kursni yaxshi o'zlashtirasiz va bu orqali chegirmalarga ega bo'lasiz. </li>
                                    <li class="quest text-primary">Qachon ball beriladi ?</li>
                                    <li class="ans pl-5">Kurs ichidagi testlarni yechish orqali (10-15 ball) <br>Online tarzda darslarni kuzatish orqali (2 ball har bir dars uchun) <br>Amaliy mashg'ulotni bajarish orqali (10 ball har bir topshiriqga) </li>
                                    <li class="quest text-primary">Vazifani qilmasa bo'ladimi ?</li>
                                    <li class="ans pl-5"> Avvalo o'ziga havola , lekin kurs rahbari sizni topshiriqlaringizni tekshirib kerakli ballarni qo'yishi uchun vazifani topshirish shart! Navbatdagi darsdan kamida 4 soat  oldin.</li>
                                    <li class="quest text-primary">Talabalar chati (Telegram)</li>
                                    <li class="ans pl-5">Kursdoshlaringiz bilan doimiy aloqada bo'ling ,tajriba almashing. Telegram orqali kurs uchun ochilgan chatlarga a'zo bo'ling.</li>
                                    <li class="quest ">Boshqa savol bor...</li>
                                    <li class="ans pl-5">Barcha savollar bilan istalgan aloqa usullaridan foydalansangiz bo'ladi, telefon, email, sayt orqali xabar qoldirish. </li>

                                </ul>
                            </div>
                        </div>

                        <div class="questions-box">
                            <div id="headingtree">
                                <button class="btn questions-title collapsed" type="button" data-toggle="collapse" data-target="#questiontree" aria-expanded="true" aria-controls="questiontree">
                                    Forum va Chat qoidalari
                                </button>
                            </div>

                            <div id="questiontree" class="collapse questions-reponse" aria-labelledby="headingtree" data-parent="#frequently-questions">
                                Forum va Chatlarda faqat darsga oid savollar, muloqot mavzusi qatiiyan texnik bo'lishi shart! <br>Haqoratlar , mavzudan tashqari gaplar cheklanadi. Portal qoidalariga amal qilamagan talabalarni Administartorlar chetlatish huquqiga ega , jumladan Forum va Chatlarda ham.<br> Portal ma'lumotlari uning yuklovchilarining mulki hiosblanadi ularni o'g'irlash va noodatiy foydalanish qonun bilan taqib qilinadi! Qoidalar bilan Qoidalar bo'limida batafsil tanishing.
                            </div>
                        </div>

                    </div>

                </div>
            </div>

        </div>
    </section>
<div class="mb-5"></div>
   <section class="footer-section-banner">
        <div class="container">
            <div class="row free-trial-footer-banner">
                <div class="col-md-8">
                    <h5 class="free-trial-footer-banner-title">Bepul sinov kurslarini boshlash uchun hoziroq ro'yhatdan o'ting</h5>
                    <p class="free-trial-footer-banner-text">Chegirmalar vaqti chegaralangan. Dasturlashni o'rganmoqchimisiz? Unda hoziroq ro'yhatdan o'ting. </p>
                </div>

                <div class="col-md-4 free-trial-footer-links d-flex mx-auto flex-column">
                    <div class="mb-auto"></div>
                    <div class="mb-auto">
                        <a class="sign-btn" href="{% url 'edu:page_views' 'signup' %}">Ro'yhatdan o'tish</a>
                        <a class="log-btn" href="{% url 'edu:page_views' 'signin' %}">Kirish</a>
                    </div>
                    <div class="mt-auto"></div>
                </div>
            </div>
        </div>
    </section>

  {% endblock %}

templates/pages/signup.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Bredh flat responsive HTML & WHMCS hosting and domains template">
    <meta name="author" content="coodiv.net (nedjai mohamed)">
    <link rel="icon" href="favicon.ico">
    <title>eduPy| A'zo bo'lish</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- main css file -->
    <link href="/static/css/main.min.css" rel="stylesheet">

</head>

<body>
    <!-- start body -->

    <div class="preloader">
        <!-- start preloader -->
        <div class="preloader-container">
            <svg version="1.1" id="L5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 0 0" xml:space="preserve">
                <circle fill="#675cda" stroke="none" cx="6" cy="50" r="6">
                    <animateTransform attributeName="transform" dur="1s" type="translate" values="0 15 ; 0 -15; 0 15" repeatCount="indefinite" begin="0.1" />
                </circle>
                <circle fill="#675cda" stroke="none" cx="30" cy="50" r="6">
                    <animateTransform attributeName="transform" dur="1s" type="translate" values="0 10 ; 0 -10; 0 10" repeatCount="indefinite" begin="0.2" />
                </circle>
                <circle fill="#675cda" stroke="none" cx="54" cy="50" r="6">
                    <animateTransform attributeName="transform" dur="1s" type="translate" values="0 5 ; 0 -5; 0 5" repeatCount="indefinite" begin="0.3" />
                </circle>
            </svg>
            <span>loading</span>
        </div>
    </div>
    <!-- end preloader -->

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="card-body text-center">
                    <a class="auth-content-logo-header" href="{% url 'edu:index'%}"><img src="/static/img/header/logo-w-f.png" alt=""></a>
                           {% if messages %}
                        {% for message in messages %}
                            <h5 class="bg-info" style="color:red; border-radius:6px;"><span>{{ message }}</span></h5>
                        {% endfor %}
                        {% else %}
                    <h3 class="mb-4 auth-login-title">Shaxsiy akkaunt ochish<span>Email va parolni kiriting. <br> <b>Parol 8 ta belgidan kam bo'lmasligi kerak va lotin harflari bilan kamida 1 ta raqam qatnashishi kerak!</b> </span></h3>
             
                    {% endif %}
                    <form action="#" method="POST">
                    <div class="input-group mb-3">
                        <input type="email" name="email" class="form-control" placeholder="Email adresingiz">
                    </div>
                    {% csrf_token %}
                    <div class="input-group mb-4">
                        <input type="password" class="form-control" name="password" placeholder="parol">
                    </div>
                    <div class="input-group mb-4">
                        <input type="password" class="form-control" name="copy_password" placeholder="parol takroran">
                    </div>

                    <button type="submit" class="btn btn-login-auth shadow-2 mb-4">A'zo bo'lish</button>
                    </form>
                    <p class="mb-0 text-white-muted">Shaxsiy akkauntizngiz bormi? <a href="{% url 'edu:page_views' 'signin' %}">Kirish</a></p>
                </div>
            </div>
        </div>
    </div>

    <!-- jquery -->
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <!-- bootstrap JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- template JavaScript -->
    <script src="/static/js/template-scripts.js"></script>
    <!-- flickity JavaScript -->
    <script src="/static/js/flickity.pkgd.min.js"></script>
    <!-- carousel JavaScript -->
    <script src="/static/owlcarousel/owl.carousel.min.js"></script>
    <!-- parallax JavaScript -->
    <script src="/static/js/parallax.min.js"></script>
    <!-- mailchamp JavaScript -->
    <script src="/static/js/mailchamp.js"></script>
    <!-- bootstrap offcanvas -->
    <script src="/static/js/bootstrap.offcanvas.min.js"></script>
    <!-- touchSwipe JavaScript -->
    <script src="/static/js/jquery.touchSwipe.min.js"></script>
</body>

</html>