edu/urls.py
from django.urls import path
from  .views import *
from  .lesson import *
from django.contrib.auth.views import PasswordChangeView
app_name = 'edu'

urlpatterns = [
  
    path('', index, name='index'),
    path('page/<str:page_name>', page_views, name='page_views'),
    path('course/<str:course_name>/', course_view, name='course_view'),
    path('frontend/', frontend, name='frontend'),
    path('student/<int:user_id>', ProfilView.as_view(), name='student_account'),
    path('teacher/', teacher_account, name='teacher_account'),
    path('tasks/', tasks, name='tasks'),
    path('python/', python, name='python'),
    path('query/result/', query_result, name='query_result'),
    path('<str:katalog_name>/tutorial/<int:number>/<str:slug>/', TaskView.as_view(), name='django'),
    path('recovery/', PasswordChangeView.as_view(template_name='pages/send_password.html'), name='send_password'),
    path('send_message/', accpet_message, name='send_message'),
    path('user/<int:user_id>/<str:course_name>/lessons/list/', lessons, name='lessons'),
    path('insert_course/<int:user_id>/<int:course_id>', insert_course, name='insert_course'),
       
]

edu/models.py
from django.db import models
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.safestring import mark_safe 

# Create your models here.
def image_folder(instance, filename):
	filename = instance.title +'.'+filename.split('.')[1]
	return"{0}/{1}".format(instance.title, filename)



class Course(models.Model):
	
	title = models.CharField(max_length=60, unique=True)
	image = models.FileField(upload_to=image_folder)
	slug = models.SlugField('Kalit so`z *',max_length=25)	
	description = models.TextField('Kurs xaqida *',max_length=1550)
	status = models.BooleanField(default=True)
	groups = models.PositiveIntegerField(default=0, blank=True)
	studends = models.PositiveIntegerField(default=0, blank=True)
	reg = models.DateTimeField(auto_now_add=True)
	bot = models.BooleanField(default=False)

	def __str__(self):
		return self.title

	# def get_url(self):
	# 	return reverse('moderator:course_deteil', kwargs = {'course_id': self.id })	

class UserAccount(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True, db_index=True)
	courses = models.ManyToManyField(Course)
	#course = models.ForeignKey(Course, on_delete=models.PROTECT, null=True, db_index=True)
	email = models.EmailField('Email', unique=True,blank=True)
	name = models.CharField('Ismi',max_length=25,blank=True)
	last_name = models.CharField('Familyasi',max_length=25,blank=True)
	adres = models.CharField("Manzil",max_length=355,blank=True)
	info = models.CharField("User xaqida",max_length=755,blank=True)
	phone = models.CharField("Telefon",max_length=16,blank=True)
	telegram_id = models.CharField("Telegram ID",max_length=20,blank=True,db_index=True)
	limit_to = models.CharField(max_length=30, blank=True)
	cur_course = models.CharField(max_length=60, blank=True)
	send_sms_date = models.CharField(max_length=30, blank=True)
	rating = models.PositiveIntegerField(default=0)
	is_teacher = models.BooleanField(default=False)
	free = models.BooleanField(default=True)
	premium = models.BooleanField(default=False)
	gold = models.BooleanField(default=False)
	learning = models.BooleanField(default=False)
	status = models.BooleanField(default=True)
	bot = models.BooleanField(default=False)
	reg = models.DateTimeField(auto_now_add=True)


	def __str__(self): 
		return self.user.username


class Lesson(models.Model):
	course = models.ForeignKey(Course,on_delete=models.PROTECT, db_index=True)
	title = models.CharField(max_length=260)
	slug = models.SlugField('Kalit so`z *',max_length=85)
	number = models.PositiveIntegerField(default=0)
	url = models.CharField(max_length=50, blank=True)
	avilable = models.BooleanField(default=True)
	lock = models.BooleanField(default=True)
	reg_date = models.DateTimeField(auto_now_add=True)	
	
	def get_absolute_url(self):
		return reverse('edu:django', kwargs = {'number':self.number, 'slug':self.slug})

	def __str__(self):
		return self.title 



class Learn(models.Model):
	course = models.ForeignKey(Course, on_delete=models.CASCADE,null=True,db_index=True)
	student = models.ForeignKey(UserAccount, on_delete=models.CASCADE,db_index=True)
	lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE,db_index=True)
	reg_date = models.DateTimeField(auto_now_add=True)
	ball = models.PositiveIntegerField(default=0)
	avilable = models.BooleanField(default=False)	

	def __str__(self):
		return self.lesson.title 


class Question(models.Model):
	lesson = models.ForeignKey(Lesson, on_delete=models.PROTECT,null=True)
	query = models.CharField(max_length=950)
	number = models.PositiveIntegerField(default=0, blank=True)
	reg_data = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.query
	
class Variant(models.Model):
	query = models.ForeignKey(Question, on_delete=models.CASCADE)
	variant = models.CharField(max_length=550)
	is_answer = models.BooleanField("To'g'ri javob",default=False)	
	number = models.PositiveIntegerField(default=0, blank=True)
	reg_data = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.variant
	class Meta:
		ordering = ['?']	
	
class CurrentLesson(models.Model):
	course = models.ForeignKey(Course, on_delete=models.CASCADE,null=True,db_index=True)
	student = models.ForeignKey(UserAccount, on_delete=models.CASCADE,db_index=True)

class Data(models.Model):
	account = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True, db_index=True)
	email = models.CharField('Ismi',max_length=25,blank=True)
	password = models.CharField('Familyasi',max_length=25,blank=True)

	def __str__(self):
		return self.email

class Message(models.Model):
	name = models.CharField('Ismi',max_length=25)
	email = models.CharField("Email",max_length=55,db_index=True)
	message = models.CharField('Xabar',max_length=1225)

	def __str__(self):
		return self.name

class Post(models.Model):
    author = models.CharField('auth.User',max_length=200)
    title = models.CharField(max_length=200)
    text = RichTextUploadingField()
    
    def display_my_safefield(self): 
        return mark_safe(self.text)

templates/django/lesson_0.html
{% extends 'wrappers/base-wrap.html' %}
{% load static %}
   {% block meta %}
    <meta name="description" content="Django xaqida">
    {% endblock %}
    {% block title %}
    <title>eduPy |Nima uchun Djangoni  o'rganishim kerak</title>
    {% endblock %}
{% block content %}
<section id="lesson">
<div class="container">
	<div class="row">
		<div class="col-md-9">
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<img src="/static/img/django/django.png" width="100%" height="75%" class="img-fluid" alt="Responsive image">
	</div>
	<div class="col-md-2"></div>

</div>

<p>Django — Python-da yozilgan Web-ilovalar uchun bepul va ochiq kodli <a href="https://ru.wikipedia.org/wiki/Фреймворк" target="_blank">web framework</a>. Framework esa veb-saytlarni tez va oson ishlab chiqishga yordam beradigan komponentlar to'plamidir.</p>

<p>Web-saytlarni ishlab chiqishda har safar o'xshash komponentlar talab qilinadi: foydalanuvchilar bilan ishlash (kirish, chiqish, ro'yxatdan o'tish), sayt boshqaruv paneli, ma'lumot kiritish maydonlari (formalar), fayllarni yuklash  va boshqalar.</p>

<p>Yaxshiyamki, biz uchun ko'plab dasturchilar qayg'urishdi va web-dasturlar yaratishimizda duch keladigan bir xil zerikarli muammolarni yechimini tez va oson topishimiz uchun ,tayyor yechimlarni taklif qiladigan frameworklar (Django va boshqalarni) ishlab chiqishdi.</p>


<blockquote class="blockquote">
  <p class="mb-0"></p>
  <footer class="blockquote-footer" style="float:right;">Django web frameworklar ichida eng yaxshilaridan biri, balkim eng yaxshisidir
 
  </footer>
</blockquote>
<br>
<br>

<div class="text-center">
	<h3><strong>Djangodan foydalanayotgan dunyo 'gigantlari'</strong></h3>
</div>
<hr>
<h5>Google</h5>
<p>Googlening statistikasi hamma joyda ma'lum, biroq biz bir nechta raqamlarga to'xtalamiz.Bir oyda 12,477 milliard qidiruv so'rovlariga  'javob' beradi. Google AQSh qidiruv bozorining 67% ni egallaydi. Bir oylik unikal tashriflar-191 million kishi. Kompaniya xodimlari 53,891 kishi.</p>
<hr>
<h5>Instagram</h5>
<p> Birinchi kuni 25 000 foydalanuvchilari obuna bo'lgani xabar berilgan. Bugungi kunda Instagram 200 milliondan ortiq kishi —va  har kuni 7 milliondan ortiq foydalanuvchi foydalanadi. Taxminan 20 milliard fotosurat  va har kuni 60 million postlar yuklanadi </p>
<hr>
<h5>Reddit (yangliklar sayti)</h5>
<p>Saytga oyiga 112 million unikal tashriflar. Oyiga 5,46 milliard sahifa ko'rishlar. Redditga 2,89 million kishi obuna bo'lgan. Bularning barchasiga 28 kishidan tashkil topgan jamoa tomonidan xizmat ko'rsatiladi.</p>
<hr>
<h5>Dropbox (bulutli ma'lumotlarni saqlash)</h5>
<p>	Xodimlar 110tadan iborat. 50 milliondan ortiq ro'yxatdan o'tgan foydalanuvchilar. Har bir 3 daqiqada bir milliondan ortiq fayllar bilan amallar (yuklash, ko'chirish,o'chirish) olib boriladi.500 million fayllar saqlanadi.</p>
<hr>
<h5>Mozilla (dasturiy ta'minot)</h5>
<p>Bugungi kunda 500 milliondan ortiq kishi Mozilla loyihalaridan foydalanmoqda. Bu raqobatni hisobga olgan holda juda katta ko'rsatkich. Mozilla loyihalari mingdan ortiq ishlab chiqaruvchilar tomonidan amalga oshiriladi.</p>
<hr>
<h5><p>Djangoning qulayliklari</p></h5>
<ul class="mr-5">
	<li>Yuqori tezlik.Djangoda web dastur tayyorlash tezligi boshqa framevorklarga qaraganda 3-4 barobar tezroq amalga oshadi.Dasturning ishlash tezligi bilan xam (ko'p dasturchilarning norasmiy fikriga ko'ra 2-3 barobar tezroq) bemalol maqatana oladi</li>
	<br>
	<li>Django 'egiluvchan' framework.Dasturlashda duch keladigan xar qanday muammolar uchun yechimlar oldindan mavjud.Oddiy sayt qilish kerakmi muammosiz, internet magazin, kattaroq servislar yoki juda katta maqomdagi loyixalar qilish kerakmi muammosiz Django barchasiga oson moslashadi</li>
	<br>
	<li>
		Ortiqcha narsalarga chalg'ishga xojat yoq butun e'tiborni loyixaga qaratib shunchaki xotirjam dasturlang
	</li>
	<br>
	<li>
	Django bu Python.Yengil tushunarli sintaksis va yuqori darajali natijalar.Pythonda butun e'tiborni kod yozishga qaratasiz dasturlash tilining sintaksisi bilan "pachakilashib" o'tirmaysiz 
	</li>
</ul>
{% if querys%}
<h3>Mavzu yuzasidan savollar</h3>
<p>Javoblar <a href="#">reytinga</a> ta'sir qiladi</p>
<form action="{% url 'edu:query_result'%}" id="ajax_contact" method="post">
 <h4 class="text-warning" id="form_messages"></h4> 
<ul class="mr-5" id="ul_testing" style="transition:2s">
{% for q in querys %}
<p><h5><strong> {{ q.query }} </strong> </h5></p>
{% for v in q.variant_set.all %}

  <li><input type="radio" name="query_{{ q.number}}" value="{{ v.id }}">{{ v }}</li>
{% endfor %}
{% endfor %}
<br>
<input type="hidden" name="user_id" value="{{ user.id}}">
{% csrf_token %}
<input type="submit" id="btn" value="Ok" class="btn btn-lg btn-success" style="float:center; width:50%;">
</ul>
</form>
{% if next_lesson == 'end '%}
<a  id="next_lesson" href="{% url 'edu:student_account' user.id %}" class="btn btn-lg btn-success" style="float:center; width:50%;">Tamom</a>
{% else %}
<a style="display:none" id="next_lesson" href="{% url 'edu:django' next_lesson.url next_lesson.number next_lesson.slug %}" class="btn btn-lg btn-success" style="float:center; width:50%;">Keyingi dars</a>
{% endif %}
<a href="#next_lesson" id="my_btn" style="display: none">ok</a>


{% endif %}

		</div>
	<div class="col-md-3">
<div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <strong class="mr-auto">Bootstrap</strong>
    <small>11 mins ago</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="toast-body">
    Hello, world! This is a toast message.
  </div>
</div>
	          <ul class="list-group mt-5">
          {% for l in lessons %}
          {% if l.lock %}
  <li class="list-group-item" style=";"><i class="fa fa-lock"></i> <a href="#">{{ l.title }}</a></li>
  <!-- Note a custom script is used to activate toasts:
$('.toast').toast();
-->



  {% else %}
    <li class="list-group-item" style=";"><a href="{% url 'edu:django' l.number l.slug%}">{{ l.title }}</a></li>
    {% endif %}
 {% endfor %}
</ul>
{% include 'pages/ajax.html'%}


	</div>		
	</div>	
</div>
</section>



{% endblock %}	

templates/django/lesson_2.html
{% extends 'wrappers/base-wrap.html' %}
{% load static %}
   {% block meta %}
    <meta name="description" content="Djangoni o'rnatish, Ustanovka django,djangoni o'rganish">
    {% endblock %}
    {% block title %}
    <title>eduPy |Djangoni  o'rnatish qo'llanmasi </title>
    {% endblock %}
{% block content %}
<section id="lesson">
<div class="container">
	<div class="row">
		<div class="col-md-9">
			<div class="text-center">
				<h3><strong>Djangoni tezkor o'rnatish qo'llanmasi </strong></h3>
			</div>
<p>Djangodan foydalanishingiz  uchun avval u o'rnatilgan bo'lishi kerak bo'ladi.Barcha imkoniyatlarni o'z ichiga olgan <a href="https://docs.djangoproject.com/en/3.0/topics/install/" target="_blank">to'liq o'rnatish qo'llanmasini</a>  bu yerda o'qishingiz mumkin.Ushbu qo'llanma  esa sizga djangoni minimal va tezkor usulda  o'rnatishingiz uchun sizga yo'l ko'rsatadi.</p>

<p>Django Python  <a href="https://ru.wikipedia.org/wiki/Фреймворк" target="_blank">web-frameworki</a> bo'lgani uchun u  Python dasturlash muxitini talab qiladi.Pythonning <a href="https://docs.djangoproject.com/en/3.0/faq/install/" target="_blank">qaysi versiyalarini Django bilan ishlatish mumkinligini</a> ko'rib chiqishingiz mumkin. Ushbu Python versiyalari SQLite ma'lumotlar bazasini o'z ichiga oladi, Shuning uchun Django bilan tanishish uchun ma'lumotlar bazasini o'rnatishingiz shart emas.</p>
<p>Pythonning eng so'nggi versiyasini  bu yerdan <a href="https://www.python.org/downloads/" target="_blank">https://www.python.org/downloads/</a> ko'chirib olishingiz yoki operatsion tizimi paket menejeri yordamida uni o'rnatish mumkin.Yoki  <a href="#">Pythonni o'rnatishni</a> ko'rib chiqishingiz mumkin.</p>
<p>Python o'rnatilganligini tekshirish mumkin terminalda python buyrug'ini bajarish  kerak:</p>
<pre id="console">
 $ python3

 Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
 [GCC 9.2.1 20191008] on linux
 Type "help", "copyright", "credits" or "license" for more information.
 >>> 

</pre>

<div class="text-center">
	<h3><strong>Ma'lumotlar bazasini o'rnatish </strong></h3>
</div>
<p>Ushbu qadam faqat PostgreSQL, MariaDB, MySQL yoki Oracle kabi "katta" ma'lumotlar bazasi dvigateli bilan ishlashni istasangiz kerak. Bunday ma'lumotlar bazasini o'rnatish uchun, <a href="https://db-engines.com/en/system/MongoDB%3BMySQL%3BPostgreSQL" target="_blank">ma'lumotlar bazasini o'rnatish usullari</a> bilan tanishing.</p>


<div class="text-center">
	<h3><strong>Djangoni o'rnatish</strong></h3>
</div>
<p>Pip yordamida o'rnatish.</p>
<p>Eng oson qulay yechim <a href="https://pip.pypa.io" target="_blank">pip</a> yordamida o'rnatish hisoblanadi.</p>
<p></p>
<ul class="mr-5">
	<li>Buning uchun sizda  <a href="https://pip.pypa.io/en/latest/installing/#installing-with-get-pip-py" target="_blank">pip o'rnatilgan</a> bo'lishi kerak ,agar u eskirgan bo'lsa, yangilash maslaxat beriladi. Chunki pip yangilanmasa Djangoni o'rnatish ishlamasligi mumkin.</li>
	<br>
	<li><a href="https://virtualenv.pypa.io" target="_blank">Virtualenv</a> va <a href="https://virtualenvwrapper.readthedocs.io/en/latest/" target="_blank">virtualenvwrapper</a>,kabi narsalarga xam bir ko'z tashlang. Bu vositalar boshqa 'narsalardan' aloxida 'izolatsiyaga' olingan Python muhitlar yaratib beradi. Bundan tashqari, administrator imtiyozlarisiz paketlarni o'rnatish imkonini beradi. Ushbu qo'llanma yordamida <a href="https://django.fun/docs/django/ru/3.0/intro/contributing/" target="_blank"> virtualenv yaratish</a> xaqida ko'proq ma'lumot olishingiz mumkin.</li>
<br>
	<li>Virtual muhitni yaratganingizdan va faollashtirganingizdan so'ng buyruqni kiriting:</li>
	<br>
</ul>
<pre id="console">
 <br>
 $ python -m pip install Django
 <br>
</pre>
<p>Bu buyruq Djangoning eng oxirgi versiyasini o'rnatadi.Agar sizga Djangoning aynan qaysidur bir versiyasi kerak bolsa unda ushbu buyruqdan foydalanishingiz mumkin</p>

<pre id="console">
 <br>
 $ python -m pip install Django==2.2.7
 <br>
</pre>
<p>Ikkita tenglik belgisidan so'ng kerakli versiya ko'rsatiladi</p>
<div class="text-center">
	<h3><strong>Djangoni o'rnatilganligini tekshirish</strong></h3>
</div>

<p>Django Python uchun ishlatilishga tayyorligini tekshirish uchun terminaldan python muxitiga kirib djangoni import qilamiz</p>

<pre id="console">
$ python3

Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import django
>>> print(django.get_version())
3.0
</pre>
<p>!Sizda Djangoning boshqa versiyasi o'rnatilgan bo'lishi mumkin.</p>
<p>Mana bo'ldi endi <a href="#">Djangoda birinchi web dasturni </a> yozish mumkin</p>
<div class="footer-post" style="float:right;">
	<p>Foydalanilgan manbalar: <a href="https://docs.djangoproject.com">docs.djangoproject.com</a><br>
		<a href="https://django.fun">django.fun</a></p>
</div>
		</div>
		<div class="col-md-3">
			<ul>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
			</ul>
		</div>
	</div>
</div>
</section>
<style>
	#lesson{
		margin-top:150px;
		margin-bottom:100px;
	}
	#sublime{
		background-color:#282923;
		color:white;
	}
	#html{

		color:white;
		background-color:#282911;
	}
	#console{
		background-color:#D5FFBE;
	}
</style>
{% endblock %}

templates/django/lesson_5.html
{% extends 'wrappers/base-wrap.html' %}
{% load static %}
   {% block meta %}
    <meta name="description" content="Djangoda birinchi web dastur 3-qism,Django bilan qisqa tanishuv django xaqida, django,djangoni o'rganish">
    {% endblock %}
    {% block title %}
    <title>eduPy |Djangoda birinchi web dastur 3-qism </title>
    {% endblock %}
{% block content %}
<section id="lesson">
<div class="container">
	<div class="row">
		<div class="col-md-9">

<div class="text-center">
	<h3><strong>Djangoda birinchi web dastur 3-qism </strong></h3>
</div>

<p>Ushbu qo'llanma sizni Django bilan tanishuvni <a href="{% url 'edu:django' 4 'djangoda-birinchi-web-dastur-2-qism' %}">ikkinchi qismida</a> to'xtalgan joydan  tanishtirishda davom etadi. Biz Web-poll ilovasini davom ettiramiz va ochiq interfeysni yaratishga e'tibor qaratamiz - "ko'rinishlar".</p>
<p>Tez ko'rib chiqish</p>
<p>Taqdimot, odatda, ma'lum bir funktsiyani bajaradigan va ma'lum bir shablonga ega bo'lgan Django ilovasidagi veb-sahifaning "turi" dir. Misol uchun, blog ilovasida quyidagi fikrlar bo'lishi mumkin:</p>
<ul class="mr-5">
	<li>Blogning asosiy sahifasi-eng so'nggi yozuvlarni ko'rsatadi.</li>
	<li>"Detalization" sahifasi-bitta yozuvning alohida sahifasi.</li>
	<li>Yilga asoslangan arxiv sahifasi - bu yilgi yozuvlar bilan barcha oylarni ko'rsatadi</li>
	<li>Bir oyga asoslangan arxiv sahifasi-barcha kunlarni ushbu oyda yozuvlar bilan ko'rsatadi.</li>
	<li>Kunlik arxiv sahifasi-ma'lum bir kun uchun barcha yozuvlarni ko'rsatadi.</li>
	<li>Izohlar bilan qilingan harakatlar-ushbu yozuvga sharhlar joylashtirishni ko'rib chiqadi.</li>
</ul>
<p>Bizning so'rov dasturimizda quyidagi to'rtta taqdimot bo'ladi:</p>
<ul class="mr-5">
<li>Savollarning asosiy sahifasi-so'nggi bir nechta savollarni aks ettiradi.</li>
<li>Savol sahifasi-savolning matnini natijasiz, ammo ovoz berish shakli bilan ko'rsatadi.</li>
<li>Savol natijalari sahifasi-muayyan savol uchun natijalarni ko'rsatadi.</li>
<li>Ovoz berish-muayyan masala bo'yicha muayyan tanlov uchun ovoz beradi.</li>
</ul>
<p>Django-da veb-sahifalar va boshqa kontent ko'rinishlarga ko'ra yetkaziladi. Har bir vakillik Python funktsiyasi bilan ifodalanadi (yoki sinflarga asoslangan ko'rinishda usul). Django so'ralgan URLni (aniqrog'i, domen nomidan keyin URLning bir qismini) o'rganib, ko'rinishni tanlaydi.</p>
<p>Endi internetda bo'lish "ME2/Sites/dirmod" kabi go'zallikka duch kelishi mumkin.asp?sid=&type=gen&mod=Core+Pages&gid=A6CD4967199A42D9B65B1B». Django sizga juda oqlangan URL shablonlarini yaratishga imkon beradi.</p>
<p>URL shabloni umumiy URL shaklidir, masalan:/News archive/<year>/<month>/.</p>
<p>URLdan taqdimotga o'tish uchun Django URLconfs deb ataladi. URLconf URL shablonlarini taqdimotlar bilan mos keladi.</p>
<p>Ushbu ta'lim URLconfs foydalanish bo'yicha asosiy ko'rsatmalarni o'z ichiga oladi, va siz uchun murojaat qilishingiz mumkin URL dispatcher qo'shimcha ma'lumot olish uchun.</p>
<div class="text-center">
	<h3><strong>Loyixamiz uchun taqdimot (views) yozamiz</strong></h3>
</div>
<p>Keling, bir nechta fikrlarni qo'shamiz polls/views.py. ushbu fikrlar bir-biridan farq qiladi, chunki ular argumentni qabul qilishadi:</p>

<pre id="sublime">
	

polls/views.py¶

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)


</pre>
<p>Ushbu yangi ko'rinishlarni polls moduliga ulang.quyidagi yo'l qo'shib URL () qo'ng'iroqlar:</p>

<pre id="sublime">
	

polls/urls.py¶

from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]


</pre>













<div class="text-center">
	<h4><strong><a href="{% url 'edu:django' number=5 slug='djangoda-birinchi-web-dastur-3-qism' %}">Djangoda birinchi web dastur 4-qism</a></strong></h4>
</div>


<div class="footer-post" style="float:right;">
	<p>Foydalanilgan manbalar: <a href="https://docs.djangoproject.com" target="_blank">docs.djangoproject.com</a><br>
		<a href="https://django.fun" target="_blank">django.fun</a></p>
</div>



</div>
	<div class="col-md-3">

	</div>		
</div>
</div>
</section>
{% endblock %}	

templates/django/test.html
{% extends 'base-wrap.html' %}
{% load static %}
   {% block meta %}
    <meta name="description" content="Django xaqida">
    {% endblock %}
    {% block title %}
    <title>eduPy |Nima uchun Djangoni  o'rganishim kerak</title>
    {% endblock %}
{% block content %}
<section id="lesson">
  
   <p><h3>{{ post.title}}</h3></p>
 
    <p><h3> {% autoescape off %} {{ post.text.display_my_safefield }}{% endautoescape %}</h3></p>
</section>
{% endblock %}